apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations: {}
  labels: {}
  name: coredns
spec:
  groups:
  - name: EmbeddedExporter
    rules:
    - alert: CorednsPanicCount
      annotations:
        description: "Number of CoreDNS panics encountered\n  VALUE = {{ $value }}\n\
          \  LABELS = {{ $labels }}"
        summary: CoreDNS Panic Count (instance {{ $labels.instance }})
      expr: increase(coredns_panics_total[1m]) > 0
      for: 0m
      labels:
        severity: critical
