apiVersion: v1
kind: Service
metadata:
  name: {{ include "hks-manager.fullname" . }}
  labels:
    {{- include "hks-manager.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  internalTrafficPolicy: {{ .Values.service.internalTrafficPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hks-manager.selectorLabels" . | nindent 4 }}
